// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiddlzqShefdxJd1Y95NADxGYPNdHBi3s',
    appId: '1:1089618147151:web:b7ba6dad37eb32db07773a',
    messagingSenderId: '1089618147151',
    projectId: 'relygo-aba85',
    authDomain: 'relygo-aba85.firebaseapp.com',
    storageBucket: 'relygo-aba85.firebasestorage.app',
    measurementId: 'G-ZHJE7GTGS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtJATmOYSooUooPzH_aSwJ75bAOjDUwxY',
    appId: '1:1089618147151:android:42762fadbdf85b8907773a',
    messagingSenderId: '1089618147151',
    projectId: 'relygo-aba85',
    storageBucket: 'relygo-aba85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLrhHEbR5--5pe9KRA7epXVI2NtqXnGsM',
    appId: '1:1089618147151:ios:8604d1114f1c5ce607773a',
    messagingSenderId: '1089618147151',
    projectId: 'relygo-aba85',
    storageBucket: 'relygo-aba85.firebasestorage.app',
    iosBundleId: 'com.example.relygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLrhHEbR5--5pe9KRA7epXVI2NtqXnGsM',
    appId: '1:1089618147151:ios:8604d1114f1c5ce607773a',
    messagingSenderId: '1089618147151',
    projectId: 'relygo-aba85',
    storageBucket: 'relygo-aba85.firebasestorage.app',
    iosBundleId: 'com.example.relygo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiddlzqShefdxJd1Y95NADxGYPNdHBi3s',
    appId: '1:1089618147151:web:c133d8c0b85e643d07773a',
    messagingSenderId: '1089618147151',
    projectId: 'relygo-aba85',
    authDomain: 'relygo-aba85.firebaseapp.com',
    storageBucket: 'relygo-aba85.firebasestorage.app',
    measurementId: 'G-SXQCV3YZ2B',
  );

}