// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALXp5_htDNwTa6CZ6bSK1GMXadHbUZwyI',
    appId: '1:415454423321:web:c9aab44c0614ba088abd88',
    messagingSenderId: '415454423321',
    projectId: 'relygonew',
    authDomain: 'relygonew.firebaseapp.com',
    storageBucket: 'relygonew.firebasestorage.app',
    measurementId: 'G-CVDWN57TW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkd1egkAqcGiDRGbLTaDbQIqjXRFlgM0E',
    appId: '1:415454423321:android:56c1e81bf371fa468abd88',
    messagingSenderId: '415454423321',
    projectId: 'relygonew',
    storageBucket: 'relygonew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJYXrnGRJ4GyP_o1U-ZfrrQpb5a0XZ1M',
    appId: '1:415454423321:ios:e789828b6683e3f88abd88',
    messagingSenderId: '415454423321',
    projectId: 'relygonew',
    storageBucket: 'relygonew.firebasestorage.app',
    iosBundleId: 'com.example.relygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpJYXrnGRJ4GyP_o1U-ZfrrQpb5a0XZ1M',
    appId: '1:415454423321:ios:e789828b6683e3f88abd88',
    messagingSenderId: '415454423321',
    projectId: 'relygonew',
    storageBucket: 'relygonew.firebasestorage.app',
    iosBundleId: 'com.example.relygo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALXp5_htDNwTa6CZ6bSK1GMXadHbUZwyI',
    appId: '1:415454423321:web:3bff534dc487713f8abd88',
    messagingSenderId: '415454423321',
    projectId: 'relygonew',
    authDomain: 'relygonew.firebaseapp.com',
    storageBucket: 'relygonew.firebasestorage.app',
    measurementId: 'G-RBRD0J0N91',
  );

}